// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'package:lazynote_flutter/core/bindings/api.dart';
import 'package:lazynote_flutter/core/bindings/frb_generated.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AtomListItem dco_decode_atom_list_item(dynamic raw);

  @protected
  AtomListResponse dco_decode_atom_list_response(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  NoteItem dco_decode_box_autoadd_note_item(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  WorkspaceNodeItem dco_decode_box_autoadd_workspace_node_item(dynamic raw);

  @protected
  EntryActionResponse dco_decode_entry_action_response(dynamic raw);

  @protected
  EntrySearchItem dco_decode_entry_search_item(dynamic raw);

  @protected
  EntrySearchResponse dco_decode_entry_search_response(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AtomListItem> dco_decode_list_atom_list_item(dynamic raw);

  @protected
  List<EntrySearchItem> dco_decode_list_entry_search_item(dynamic raw);

  @protected
  List<NoteItem> dco_decode_list_note_item(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<WorkspaceNodeItem> dco_decode_list_workspace_node_item(dynamic raw);

  @protected
  NoteItem dco_decode_note_item(dynamic raw);

  @protected
  NoteResponse dco_decode_note_response(dynamic raw);

  @protected
  NotesListResponse dco_decode_notes_list_response(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  NoteItem? dco_decode_opt_box_autoadd_note_item(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  WorkspaceNodeItem? dco_decode_opt_box_autoadd_workspace_node_item(
    dynamic raw,
  );

  @protected
  TagsListResponse dco_decode_tags_list_response(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WorkspaceActionResponse dco_decode_workspace_action_response(dynamic raw);

  @protected
  WorkspaceListChildrenResponse dco_decode_workspace_list_children_response(
    dynamic raw,
  );

  @protected
  WorkspaceNodeItem dco_decode_workspace_node_item(dynamic raw);

  @protected
  WorkspaceNodeResponse dco_decode_workspace_node_response(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AtomListItem sse_decode_atom_list_item(SseDeserializer deserializer);

  @protected
  AtomListResponse sse_decode_atom_list_response(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  NoteItem sse_decode_box_autoadd_note_item(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  WorkspaceNodeItem sse_decode_box_autoadd_workspace_node_item(
    SseDeserializer deserializer,
  );

  @protected
  EntryActionResponse sse_decode_entry_action_response(
    SseDeserializer deserializer,
  );

  @protected
  EntrySearchItem sse_decode_entry_search_item(SseDeserializer deserializer);

  @protected
  EntrySearchResponse sse_decode_entry_search_response(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AtomListItem> sse_decode_list_atom_list_item(
    SseDeserializer deserializer,
  );

  @protected
  List<EntrySearchItem> sse_decode_list_entry_search_item(
    SseDeserializer deserializer,
  );

  @protected
  List<NoteItem> sse_decode_list_note_item(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<WorkspaceNodeItem> sse_decode_list_workspace_node_item(
    SseDeserializer deserializer,
  );

  @protected
  NoteItem sse_decode_note_item(SseDeserializer deserializer);

  @protected
  NoteResponse sse_decode_note_response(SseDeserializer deserializer);

  @protected
  NotesListResponse sse_decode_notes_list_response(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  NoteItem? sse_decode_opt_box_autoadd_note_item(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  WorkspaceNodeItem? sse_decode_opt_box_autoadd_workspace_node_item(
    SseDeserializer deserializer,
  );

  @protected
  TagsListResponse sse_decode_tags_list_response(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WorkspaceActionResponse sse_decode_workspace_action_response(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceListChildrenResponse sse_decode_workspace_list_children_response(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceNodeItem sse_decode_workspace_node_item(
    SseDeserializer deserializer,
  );

  @protected
  WorkspaceNodeResponse sse_decode_workspace_node_response(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_atom_list_item(AtomListItem self, SseSerializer serializer);

  @protected
  void sse_encode_atom_list_response(
    AtomListResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_note_item(
    NoteItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_workspace_node_item(
    WorkspaceNodeItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_entry_action_response(
    EntryActionResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_entry_search_item(
    EntrySearchItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_entry_search_response(
    EntrySearchResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_atom_list_item(
    List<AtomListItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_entry_search_item(
    List<EntrySearchItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_note_item(List<NoteItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_workspace_node_item(
    List<WorkspaceNodeItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_note_item(NoteItem self, SseSerializer serializer);

  @protected
  void sse_encode_note_response(NoteResponse self, SseSerializer serializer);

  @protected
  void sse_encode_notes_list_response(
    NotesListResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_note_item(
    NoteItem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_workspace_node_item(
    WorkspaceNodeItem? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tags_list_response(
    TagsListResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_workspace_action_response(
    WorkspaceActionResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_list_children_response(
    WorkspaceListChildrenResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_node_item(
    WorkspaceNodeItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_workspace_node_response(
    WorkspaceNodeResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
