// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:lazynote_flutter/core/bindings/api.dart';
import 'package:lazynote_flutter/core/bindings/frb_generated.dart';
import 'package:lazynote_flutter/core/bindings/frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1852740980;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'lazynote_ffi',
        ioDirectory: '../../crates/lazynote_ffi/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<EntryActionResponse> crateApiAtomUpdateStatus({
    required String atomId,
    String? status,
  });

  Future<AtomListResponse> crateApiCalendarListByRange({
    required PlatformInt64 startMs,
    required PlatformInt64 endMs,
    int? limit,
    int? offset,
  });

  Future<EntryActionResponse> crateApiCalendarUpdateEvent({
    required String atomId,
    required PlatformInt64 startMs,
    required PlatformInt64 endMs,
  });

  String crateApiConfigureEntryDbPath({required String dbPath});

  String crateApiCoreVersion();

  Future<EntryActionResponse> crateApiEntryCreateNote({
    required String content,
  });

  Future<EntryActionResponse> crateApiEntryCreateTask({
    required String content,
  });

  Future<EntryActionResponse> crateApiEntrySchedule({
    required String title,
    required PlatformInt64 startEpochMs,
    PlatformInt64? endEpochMs,
  });

  Future<EntrySearchResponse> crateApiEntrySearch({
    required String text,
    String? kind,
    int? limit,
  });

  String crateApiInitLogging({required String level, required String logDir});

  Future<NoteResponse> crateApiNoteCreate({required String content});

  Future<NoteResponse> crateApiNoteGet({required String atomId});

  Future<NoteResponse> crateApiNoteSetTags({
    required String atomId,
    required List<String> tags,
  });

  Future<NoteResponse> crateApiNoteUpdate({
    required String atomId,
    required String content,
  });

  Future<NotesListResponse> crateApiNotesList({
    String? tag,
    int? limit,
    int? offset,
  });

  String crateApiPing();

  Future<TagsListResponse> crateApiTagsList();

  Future<AtomListResponse> crateApiTasksListInbox({int? limit, int? offset});

  Future<AtomListResponse> crateApiTasksListToday({
    required PlatformInt64 bodMs,
    required PlatformInt64 eodMs,
    int? limit,
    int? offset,
  });

  Future<AtomListResponse> crateApiTasksListUpcoming({
    required PlatformInt64 eodMs,
    int? limit,
    int? offset,
  });

  Future<WorkspaceNodeResponse> crateApiWorkspaceCreateFolder({
    String? parentNodeId,
    required String name,
  });

  Future<WorkspaceNodeResponse> crateApiWorkspaceCreateNoteRef({
    String? parentNodeId,
    required String atomId,
    String? displayName,
  });

  Future<WorkspaceActionResponse> crateApiWorkspaceDeleteFolder({
    required String nodeId,
    required String mode,
  });

  Future<WorkspaceListChildrenResponse> crateApiWorkspaceListChildren({
    String? parentNodeId,
  });

  Future<WorkspaceActionResponse> crateApiWorkspaceMoveNode({
    required String nodeId,
    String? newParentId,
    PlatformInt64? targetOrder,
  });

  Future<WorkspaceActionResponse> crateApiWorkspaceRenameNode({
    required String nodeId,
    required String newName,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<EntryActionResponse> crateApiAtomUpdateStatus({
    required String atomId,
    String? status,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(atomId, serializer);
          sse_encode_opt_String(status, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_entry_action_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAtomUpdateStatusConstMeta,
        argValues: [atomId, status],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAtomUpdateStatusConstMeta => const TaskConstMeta(
    debugName: 'atom_update_status',
    argNames: ['atomId', 'status'],
  );

  @override
  Future<AtomListResponse> crateApiCalendarListByRange({
    required PlatformInt64 startMs,
    required PlatformInt64 endMs,
    int? limit,
    int? offset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(startMs, serializer);
          sse_encode_i_64(endMs, serializer);
          sse_encode_opt_box_autoadd_u_32(limit, serializer);
          sse_encode_opt_box_autoadd_u_32(offset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_atom_list_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCalendarListByRangeConstMeta,
        argValues: [startMs, endMs, limit, offset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalendarListByRangeConstMeta =>
      const TaskConstMeta(
        debugName: 'calendar_list_by_range',
        argNames: ['startMs', 'endMs', 'limit', 'offset'],
      );

  @override
  Future<EntryActionResponse> crateApiCalendarUpdateEvent({
    required String atomId,
    required PlatformInt64 startMs,
    required PlatformInt64 endMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(atomId, serializer);
          sse_encode_i_64(startMs, serializer);
          sse_encode_i_64(endMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_entry_action_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCalendarUpdateEventConstMeta,
        argValues: [atomId, startMs, endMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCalendarUpdateEventConstMeta =>
      const TaskConstMeta(
        debugName: 'calendar_update_event',
        argNames: ['atomId', 'startMs', 'endMs'],
      );

  @override
  String crateApiConfigureEntryDbPath({required String dbPath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiConfigureEntryDbPathConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConfigureEntryDbPathConstMeta =>
      const TaskConstMeta(
        debugName: 'configure_entry_db_path',
        argNames: ['dbPath'],
      );

  @override
  String crateApiCoreVersion() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreVersionConstMeta =>
      const TaskConstMeta(debugName: 'core_version', argNames: []);

  @override
  Future<EntryActionResponse> crateApiEntryCreateNote({
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_entry_action_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEntryCreateNoteConstMeta,
        argValues: [content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntryCreateNoteConstMeta => const TaskConstMeta(
    debugName: 'entry_create_note',
    argNames: ['content'],
  );

  @override
  Future<EntryActionResponse> crateApiEntryCreateTask({
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_entry_action_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEntryCreateTaskConstMeta,
        argValues: [content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntryCreateTaskConstMeta => const TaskConstMeta(
    debugName: 'entry_create_task',
    argNames: ['content'],
  );

  @override
  Future<EntryActionResponse> crateApiEntrySchedule({
    required String title,
    required PlatformInt64 startEpochMs,
    PlatformInt64? endEpochMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(title, serializer);
          sse_encode_i_64(startEpochMs, serializer);
          sse_encode_opt_box_autoadd_i_64(endEpochMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_entry_action_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEntryScheduleConstMeta,
        argValues: [title, startEpochMs, endEpochMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntryScheduleConstMeta => const TaskConstMeta(
    debugName: 'entry_schedule',
    argNames: ['title', 'startEpochMs', 'endEpochMs'],
  );

  @override
  Future<EntrySearchResponse> crateApiEntrySearch({
    required String text,
    String? kind,
    int? limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_opt_String(kind, serializer);
          sse_encode_opt_box_autoadd_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_entry_search_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEntrySearchConstMeta,
        argValues: [text, kind, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEntrySearchConstMeta => const TaskConstMeta(
    debugName: 'entry_search',
    argNames: ['text', 'kind', 'limit'],
  );

  @override
  String crateApiInitLogging({required String level, required String logDir}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(level, serializer);
          sse_encode_String(logDir, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitLoggingConstMeta,
        argValues: [level, logDir],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitLoggingConstMeta => const TaskConstMeta(
    debugName: 'init_logging',
    argNames: ['level', 'logDir'],
  );

  @override
  Future<NoteResponse> crateApiNoteCreate({required String content}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_note_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNoteCreateConstMeta,
        argValues: [content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNoteCreateConstMeta =>
      const TaskConstMeta(debugName: 'note_create', argNames: ['content']);

  @override
  Future<NoteResponse> crateApiNoteGet({required String atomId}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(atomId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_note_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNoteGetConstMeta,
        argValues: [atomId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNoteGetConstMeta =>
      const TaskConstMeta(debugName: 'note_get', argNames: ['atomId']);

  @override
  Future<NoteResponse> crateApiNoteSetTags({
    required String atomId,
    required List<String> tags,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(atomId, serializer);
          sse_encode_list_String(tags, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_note_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNoteSetTagsConstMeta,
        argValues: [atomId, tags],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNoteSetTagsConstMeta => const TaskConstMeta(
    debugName: 'note_set_tags',
    argNames: ['atomId', 'tags'],
  );

  @override
  Future<NoteResponse> crateApiNoteUpdate({
    required String atomId,
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(atomId, serializer);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_note_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNoteUpdateConstMeta,
        argValues: [atomId, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNoteUpdateConstMeta => const TaskConstMeta(
    debugName: 'note_update',
    argNames: ['atomId', 'content'],
  );

  @override
  Future<NotesListResponse> crateApiNotesList({
    String? tag,
    int? limit,
    int? offset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(tag, serializer);
          sse_encode_opt_box_autoadd_u_32(limit, serializer);
          sse_encode_opt_box_autoadd_u_32(offset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_notes_list_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiNotesListConstMeta,
        argValues: [tag, limit, offset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNotesListConstMeta => const TaskConstMeta(
    debugName: 'notes_list',
    argNames: ['tag', 'limit', 'offset'],
  );

  @override
  String crateApiPing() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPingConstMeta =>
      const TaskConstMeta(debugName: 'ping', argNames: []);

  @override
  Future<TagsListResponse> crateApiTagsList() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_tags_list_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTagsListConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTagsListConstMeta =>
      const TaskConstMeta(debugName: 'tags_list', argNames: []);

  @override
  Future<AtomListResponse> crateApiTasksListInbox({int? limit, int? offset}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_box_autoadd_u_32(limit, serializer);
          sse_encode_opt_box_autoadd_u_32(offset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_atom_list_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTasksListInboxConstMeta,
        argValues: [limit, offset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTasksListInboxConstMeta => const TaskConstMeta(
    debugName: 'tasks_list_inbox',
    argNames: ['limit', 'offset'],
  );

  @override
  Future<AtomListResponse> crateApiTasksListToday({
    required PlatformInt64 bodMs,
    required PlatformInt64 eodMs,
    int? limit,
    int? offset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(bodMs, serializer);
          sse_encode_i_64(eodMs, serializer);
          sse_encode_opt_box_autoadd_u_32(limit, serializer);
          sse_encode_opt_box_autoadd_u_32(offset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_atom_list_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTasksListTodayConstMeta,
        argValues: [bodMs, eodMs, limit, offset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTasksListTodayConstMeta => const TaskConstMeta(
    debugName: 'tasks_list_today',
    argNames: ['bodMs', 'eodMs', 'limit', 'offset'],
  );

  @override
  Future<AtomListResponse> crateApiTasksListUpcoming({
    required PlatformInt64 eodMs,
    int? limit,
    int? offset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_i_64(eodMs, serializer);
          sse_encode_opt_box_autoadd_u_32(limit, serializer);
          sse_encode_opt_box_autoadd_u_32(offset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_atom_list_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTasksListUpcomingConstMeta,
        argValues: [eodMs, limit, offset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTasksListUpcomingConstMeta => const TaskConstMeta(
    debugName: 'tasks_list_upcoming',
    argNames: ['eodMs', 'limit', 'offset'],
  );

  @override
  Future<WorkspaceNodeResponse> crateApiWorkspaceCreateFolder({
    String? parentNodeId,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(parentNodeId, serializer);
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_workspace_node_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWorkspaceCreateFolderConstMeta,
        argValues: [parentNodeId, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceCreateFolderConstMeta =>
      const TaskConstMeta(
        debugName: 'workspace_create_folder',
        argNames: ['parentNodeId', 'name'],
      );

  @override
  Future<WorkspaceNodeResponse> crateApiWorkspaceCreateNoteRef({
    String? parentNodeId,
    required String atomId,
    String? displayName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(parentNodeId, serializer);
          sse_encode_String(atomId, serializer);
          sse_encode_opt_String(displayName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_workspace_node_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWorkspaceCreateNoteRefConstMeta,
        argValues: [parentNodeId, atomId, displayName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceCreateNoteRefConstMeta =>
      const TaskConstMeta(
        debugName: 'workspace_create_note_ref',
        argNames: ['parentNodeId', 'atomId', 'displayName'],
      );

  @override
  Future<WorkspaceActionResponse> crateApiWorkspaceDeleteFolder({
    required String nodeId,
    required String mode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nodeId, serializer);
          sse_encode_String(mode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_workspace_action_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWorkspaceDeleteFolderConstMeta,
        argValues: [nodeId, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceDeleteFolderConstMeta =>
      const TaskConstMeta(
        debugName: 'workspace_delete_folder',
        argNames: ['nodeId', 'mode'],
      );

  @override
  Future<WorkspaceListChildrenResponse> crateApiWorkspaceListChildren({
    String? parentNodeId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(parentNodeId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_workspace_list_children_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWorkspaceListChildrenConstMeta,
        argValues: [parentNodeId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceListChildrenConstMeta =>
      const TaskConstMeta(
        debugName: 'workspace_list_children',
        argNames: ['parentNodeId'],
      );

  @override
  Future<WorkspaceActionResponse> crateApiWorkspaceMoveNode({
    required String nodeId,
    String? newParentId,
    PlatformInt64? targetOrder,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nodeId, serializer);
          sse_encode_opt_String(newParentId, serializer);
          sse_encode_opt_box_autoadd_i_64(targetOrder, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_workspace_action_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWorkspaceMoveNodeConstMeta,
        argValues: [nodeId, newParentId, targetOrder],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceMoveNodeConstMeta => const TaskConstMeta(
    debugName: 'workspace_move_node',
    argNames: ['nodeId', 'newParentId', 'targetOrder'],
  );

  @override
  Future<WorkspaceActionResponse> crateApiWorkspaceRenameNode({
    required String nodeId,
    required String newName,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nodeId, serializer);
          sse_encode_String(newName, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_workspace_action_response,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWorkspaceRenameNodeConstMeta,
        argValues: [nodeId, newName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWorkspaceRenameNodeConstMeta =>
      const TaskConstMeta(
        debugName: 'workspace_rename_node',
        argNames: ['nodeId', 'newName'],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AtomListItem dco_decode_atom_list_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return AtomListItem(
      atomId: dco_decode_String(arr[0]),
      kind: dco_decode_String(arr[1]),
      content: dco_decode_String(arr[2]),
      previewText: dco_decode_opt_String(arr[3]),
      previewImage: dco_decode_opt_String(arr[4]),
      tags: dco_decode_list_String(arr[5]),
      startAt: dco_decode_opt_box_autoadd_i_64(arr[6]),
      endAt: dco_decode_opt_box_autoadd_i_64(arr[7]),
      taskStatus: dco_decode_opt_String(arr[8]),
      updatedAt: dco_decode_i_64(arr[9]),
    );
  }

  @protected
  AtomListResponse dco_decode_atom_list_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return AtomListResponse(
      ok: dco_decode_bool(arr[0]),
      errorCode: dco_decode_opt_String(arr[1]),
      message: dco_decode_String(arr[2]),
      items: dco_decode_list_atom_list_item(arr[3]),
      appliedLimit: dco_decode_u_32(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  NoteItem dco_decode_box_autoadd_note_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_note_item(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  WorkspaceNodeItem dco_decode_box_autoadd_workspace_node_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_workspace_node_item(raw);
  }

  @protected
  EntryActionResponse dco_decode_entry_action_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return EntryActionResponse(
      ok: dco_decode_bool(arr[0]),
      atomId: dco_decode_opt_String(arr[1]),
      message: dco_decode_String(arr[2]),
    );
  }

  @protected
  EntrySearchItem dco_decode_entry_search_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return EntrySearchItem(
      atomId: dco_decode_String(arr[0]),
      kind: dco_decode_String(arr[1]),
      snippet: dco_decode_String(arr[2]),
    );
  }

  @protected
  EntrySearchResponse dco_decode_entry_search_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return EntrySearchResponse(
      ok: dco_decode_bool(arr[0]),
      errorCode: dco_decode_opt_String(arr[1]),
      items: dco_decode_list_entry_search_item(arr[2]),
      message: dco_decode_String(arr[3]),
      appliedLimit: dco_decode_u_32(arr[4]),
    );
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AtomListItem> dco_decode_list_atom_list_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_atom_list_item).toList();
  }

  @protected
  List<EntrySearchItem> dco_decode_list_entry_search_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_entry_search_item).toList();
  }

  @protected
  List<NoteItem> dco_decode_list_note_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_note_item).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<WorkspaceNodeItem> dco_decode_list_workspace_node_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_workspace_node_item).toList();
  }

  @protected
  NoteItem dco_decode_note_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return NoteItem(
      atomId: dco_decode_String(arr[0]),
      content: dco_decode_String(arr[1]),
      previewText: dco_decode_opt_String(arr[2]),
      previewImage: dco_decode_opt_String(arr[3]),
      updatedAt: dco_decode_i_64(arr[4]),
      tags: dco_decode_list_String(arr[5]),
    );
  }

  @protected
  NoteResponse dco_decode_note_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return NoteResponse(
      ok: dco_decode_bool(arr[0]),
      errorCode: dco_decode_opt_String(arr[1]),
      message: dco_decode_String(arr[2]),
      note: dco_decode_opt_box_autoadd_note_item(arr[3]),
    );
  }

  @protected
  NotesListResponse dco_decode_notes_list_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return NotesListResponse(
      ok: dco_decode_bool(arr[0]),
      errorCode: dco_decode_opt_String(arr[1]),
      message: dco_decode_String(arr[2]),
      items: dco_decode_list_note_item(arr[3]),
      appliedLimit: dco_decode_u_32(arr[4]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  NoteItem? dco_decode_opt_box_autoadd_note_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_note_item(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  WorkspaceNodeItem? dco_decode_opt_box_autoadd_workspace_node_item(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_workspace_node_item(raw);
  }

  @protected
  TagsListResponse dco_decode_tags_list_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TagsListResponse(
      ok: dco_decode_bool(arr[0]),
      errorCode: dco_decode_opt_String(arr[1]),
      message: dco_decode_String(arr[2]),
      tags: dco_decode_list_String(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WorkspaceActionResponse dco_decode_workspace_action_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return WorkspaceActionResponse(
      ok: dco_decode_bool(arr[0]),
      errorCode: dco_decode_opt_String(arr[1]),
      message: dco_decode_String(arr[2]),
    );
  }

  @protected
  WorkspaceListChildrenResponse dco_decode_workspace_list_children_response(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return WorkspaceListChildrenResponse(
      ok: dco_decode_bool(arr[0]),
      errorCode: dco_decode_opt_String(arr[1]),
      message: dco_decode_String(arr[2]),
      items: dco_decode_list_workspace_node_item(arr[3]),
    );
  }

  @protected
  WorkspaceNodeItem dco_decode_workspace_node_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return WorkspaceNodeItem(
      nodeId: dco_decode_String(arr[0]),
      kind: dco_decode_String(arr[1]),
      parentNodeId: dco_decode_opt_String(arr[2]),
      atomId: dco_decode_opt_String(arr[3]),
      displayName: dco_decode_String(arr[4]),
      sortOrder: dco_decode_i_64(arr[5]),
    );
  }

  @protected
  WorkspaceNodeResponse dco_decode_workspace_node_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return WorkspaceNodeResponse(
      ok: dco_decode_bool(arr[0]),
      errorCode: dco_decode_opt_String(arr[1]),
      message: dco_decode_String(arr[2]),
      node: dco_decode_opt_box_autoadd_workspace_node_item(arr[3]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AtomListItem sse_decode_atom_list_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_atomId = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_previewText = sse_decode_opt_String(deserializer);
    var var_previewImage = sse_decode_opt_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    var var_startAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_endAt = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_taskStatus = sse_decode_opt_String(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    return AtomListItem(
      atomId: var_atomId,
      kind: var_kind,
      content: var_content,
      previewText: var_previewText,
      previewImage: var_previewImage,
      tags: var_tags,
      startAt: var_startAt,
      endAt: var_endAt,
      taskStatus: var_taskStatus,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  AtomListResponse sse_decode_atom_list_response(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_errorCode = sse_decode_opt_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_items = sse_decode_list_atom_list_item(deserializer);
    var var_appliedLimit = sse_decode_u_32(deserializer);
    return AtomListResponse(
      ok: var_ok,
      errorCode: var_errorCode,
      message: var_message,
      items: var_items,
      appliedLimit: var_appliedLimit,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  NoteItem sse_decode_box_autoadd_note_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_note_item(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  WorkspaceNodeItem sse_decode_box_autoadd_workspace_node_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_workspace_node_item(deserializer));
  }

  @protected
  EntryActionResponse sse_decode_entry_action_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_atomId = sse_decode_opt_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    return EntryActionResponse(
      ok: var_ok,
      atomId: var_atomId,
      message: var_message,
    );
  }

  @protected
  EntrySearchItem sse_decode_entry_search_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_atomId = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_snippet = sse_decode_String(deserializer);
    return EntrySearchItem(
      atomId: var_atomId,
      kind: var_kind,
      snippet: var_snippet,
    );
  }

  @protected
  EntrySearchResponse sse_decode_entry_search_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_errorCode = sse_decode_opt_String(deserializer);
    var var_items = sse_decode_list_entry_search_item(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_appliedLimit = sse_decode_u_32(deserializer);
    return EntrySearchResponse(
      ok: var_ok,
      errorCode: var_errorCode,
      items: var_items,
      message: var_message,
      appliedLimit: var_appliedLimit,
    );
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AtomListItem> sse_decode_list_atom_list_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AtomListItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_atom_list_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<EntrySearchItem> sse_decode_list_entry_search_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <EntrySearchItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_entry_search_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<NoteItem> sse_decode_list_note_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NoteItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_note_item(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<WorkspaceNodeItem> sse_decode_list_workspace_node_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <WorkspaceNodeItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_workspace_node_item(deserializer));
    }
    return ans_;
  }

  @protected
  NoteItem sse_decode_note_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_atomId = sse_decode_String(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_previewText = sse_decode_opt_String(deserializer);
    var var_previewImage = sse_decode_opt_String(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    return NoteItem(
      atomId: var_atomId,
      content: var_content,
      previewText: var_previewText,
      previewImage: var_previewImage,
      updatedAt: var_updatedAt,
      tags: var_tags,
    );
  }

  @protected
  NoteResponse sse_decode_note_response(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_errorCode = sse_decode_opt_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_note = sse_decode_opt_box_autoadd_note_item(deserializer);
    return NoteResponse(
      ok: var_ok,
      errorCode: var_errorCode,
      message: var_message,
      note: var_note,
    );
  }

  @protected
  NotesListResponse sse_decode_notes_list_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_errorCode = sse_decode_opt_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_items = sse_decode_list_note_item(deserializer);
    var var_appliedLimit = sse_decode_u_32(deserializer);
    return NotesListResponse(
      ok: var_ok,
      errorCode: var_errorCode,
      message: var_message,
      items: var_items,
      appliedLimit: var_appliedLimit,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  NoteItem? sse_decode_opt_box_autoadd_note_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_note_item(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  WorkspaceNodeItem? sse_decode_opt_box_autoadd_workspace_node_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_workspace_node_item(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TagsListResponse sse_decode_tags_list_response(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_errorCode = sse_decode_opt_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_tags = sse_decode_list_String(deserializer);
    return TagsListResponse(
      ok: var_ok,
      errorCode: var_errorCode,
      message: var_message,
      tags: var_tags,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WorkspaceActionResponse sse_decode_workspace_action_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_errorCode = sse_decode_opt_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    return WorkspaceActionResponse(
      ok: var_ok,
      errorCode: var_errorCode,
      message: var_message,
    );
  }

  @protected
  WorkspaceListChildrenResponse sse_decode_workspace_list_children_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_errorCode = sse_decode_opt_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_items = sse_decode_list_workspace_node_item(deserializer);
    return WorkspaceListChildrenResponse(
      ok: var_ok,
      errorCode: var_errorCode,
      message: var_message,
      items: var_items,
    );
  }

  @protected
  WorkspaceNodeItem sse_decode_workspace_node_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nodeId = sse_decode_String(deserializer);
    var var_kind = sse_decode_String(deserializer);
    var var_parentNodeId = sse_decode_opt_String(deserializer);
    var var_atomId = sse_decode_opt_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_sortOrder = sse_decode_i_64(deserializer);
    return WorkspaceNodeItem(
      nodeId: var_nodeId,
      kind: var_kind,
      parentNodeId: var_parentNodeId,
      atomId: var_atomId,
      displayName: var_displayName,
      sortOrder: var_sortOrder,
    );
  }

  @protected
  WorkspaceNodeResponse sse_decode_workspace_node_response(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ok = sse_decode_bool(deserializer);
    var var_errorCode = sse_decode_opt_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_node = sse_decode_opt_box_autoadd_workspace_node_item(deserializer);
    return WorkspaceNodeResponse(
      ok: var_ok,
      errorCode: var_errorCode,
      message: var_message,
      node: var_node,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_atom_list_item(AtomListItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.atomId, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_opt_String(self.previewText, serializer);
    sse_encode_opt_String(self.previewImage, serializer);
    sse_encode_list_String(self.tags, serializer);
    sse_encode_opt_box_autoadd_i_64(self.startAt, serializer);
    sse_encode_opt_box_autoadd_i_64(self.endAt, serializer);
    sse_encode_opt_String(self.taskStatus, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_atom_list_response(
    AtomListResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_opt_String(self.errorCode, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_list_atom_list_item(self.items, serializer);
    sse_encode_u_32(self.appliedLimit, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_note_item(
    NoteItem self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_note_item(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_workspace_node_item(
    WorkspaceNodeItem self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_workspace_node_item(self, serializer);
  }

  @protected
  void sse_encode_entry_action_response(
    EntryActionResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_opt_String(self.atomId, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_entry_search_item(
    EntrySearchItem self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.atomId, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_String(self.snippet, serializer);
  }

  @protected
  void sse_encode_entry_search_response(
    EntrySearchResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_opt_String(self.errorCode, serializer);
    sse_encode_list_entry_search_item(self.items, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_u_32(self.appliedLimit, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_atom_list_item(
    List<AtomListItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_atom_list_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_entry_search_item(
    List<EntrySearchItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_entry_search_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_note_item(
    List<NoteItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_note_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_workspace_node_item(
    List<WorkspaceNodeItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_workspace_node_item(item, serializer);
    }
  }

  @protected
  void sse_encode_note_item(NoteItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.atomId, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_opt_String(self.previewText, serializer);
    sse_encode_opt_String(self.previewImage, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
    sse_encode_list_String(self.tags, serializer);
  }

  @protected
  void sse_encode_note_response(NoteResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_opt_String(self.errorCode, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_opt_box_autoadd_note_item(self.note, serializer);
  }

  @protected
  void sse_encode_notes_list_response(
    NotesListResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_opt_String(self.errorCode, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_list_note_item(self.items, serializer);
    sse_encode_u_32(self.appliedLimit, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_note_item(
    NoteItem? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_note_item(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_workspace_node_item(
    WorkspaceNodeItem? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_workspace_node_item(self, serializer);
    }
  }

  @protected
  void sse_encode_tags_list_response(
    TagsListResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_opt_String(self.errorCode, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_list_String(self.tags, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_workspace_action_response(
    WorkspaceActionResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_opt_String(self.errorCode, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_workspace_list_children_response(
    WorkspaceListChildrenResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_opt_String(self.errorCode, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_list_workspace_node_item(self.items, serializer);
  }

  @protected
  void sse_encode_workspace_node_item(
    WorkspaceNodeItem self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.nodeId, serializer);
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_String(self.parentNodeId, serializer);
    sse_encode_opt_String(self.atomId, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_i_64(self.sortOrder, serializer);
  }

  @protected
  void sse_encode_workspace_node_response(
    WorkspaceNodeResponse self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.ok, serializer);
    sse_encode_opt_String(self.errorCode, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_opt_box_autoadd_workspace_node_item(self.node, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
